[package]
name = "voicecoach"
version = "0.1.0"
description = "AI-powered real-time sales coaching desktop application"
authors = ["VoiceCoach Team"]
license = "MIT"
repository = ""
default-run = "voicecoach"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6", features = [ "dialog-ask", "window-close", "window-hide", "fs-remove-file", "fs-rename-file", "fs-read-file", "fs-remove-dir", "fs-read-dir", "window-maximize", "system-tray", "notification-all", "fs-copy-file", "window-unminimize", "dialog-open", "window-unmaximize", "fs-write-file", "fs-exists", "window-start-dragging", "window-show", "fs-create-dir", "dialog-message", "dialog-confirm", "window-minimize", "dialog-save", "shell-open"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
# Audio processing dependencies
cpal = "0.15.2"
rodio = "0.17.3"
hound = "3.5.0"
# Inter-process communication for Python bridge
parking_lot = "0.12.1"
crossbeam-channel = "0.5.8"
# Async utilities
futures = "0.3.28"
# Time handling
chrono = { version = "0.4", features = ["serde"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
